In [1]:
from tfg.alphaZero import create_alphazero, AlphaZero
from tfg.alphaZeroCallbacks import GameStore
from tfg.alphaZeroAdapters import TicTacToeAdapter
from tfg.util import enable_gpu, play
from tfg.strategies import Minimax, MonteCarloTree
from game.tictactoe import TicTacToe

In [2]:
enable_gpu()

game = TicTacToe()

In [4]:
store = GameStore()

alphazero = create_alphazero(game, TicTacToeAdapter(),
                             max_workers=10, self_play_times=120,
                             max_games_counter=1920, buffer_size=1500,
                             callbacks=[store], mcts_iter=400, c_puct=1,
                             exploration_noise=(.25, .045), epochs=20, batch_size=512)

Epoch 1/20
16/16 - 4s - loss: 1.5844 - value_head_loss: 0.6146 - policy_head_loss: 2.2427
Epoch 2/20
16/16 - 0s - loss: 1.5801 - value_head_loss: 0.5067 - policy_head_loss: 2.1871
Epoch 3/20
16/16 - 0s - loss: 1.5656 - value_head_loss: 0.4661 - policy_head_loss: 2.1811
Epoch 4/20
16/16 - 0s - loss: 1.5444 - value_head_loss: 0.4556 - policy_head_loss: 2.1721
Epoch 5/20
16/16 - 0s - loss: 1.5020 - value_head_loss: 0.4272 - policy_head_loss: 2.1459
Epoch 6/20
16/16 - 0s - loss: 1.4518 - value_head_loss: 0.4147 - policy_head_loss: 2.0870
Epoch 7/20
16/16 - 0s - loss: 1.3838 - value_head_loss: 0.3906 - policy_head_loss: 1.9971
Epoch 8/20
16/16 - 0s - loss: 1.3422 - value_head_loss: 0.3893 - policy_head_loss: 1.9273
Epoch 9/20
16/16 - 0s - loss: 1.2973 - value_head_loss: 0.3766 - policy_head_loss: 1.8581
Epoch 10/20
16/16 - 0s - loss: 1.2670 - value_head_loss: 0.3640 - policy_head_loss: 1.8173
Epoch 11/20
16/16 - 0s - loss: 1.2091 - value_head_loss: 0.3481 - policy_head_loss: 1.7239
Epoch 12

Epoch 11/20
16/16 - 0s - loss: 0.5706 - value_head_loss: 0.0856 - policy_head_loss: 0.9452
Epoch 12/20
16/16 - 0s - loss: 0.5765 - value_head_loss: 0.0903 - policy_head_loss: 0.9528
Epoch 13/20
16/16 - 0s - loss: 0.5836 - value_head_loss: 0.0958 - policy_head_loss: 0.9570
Epoch 14/20
16/16 - 0s - loss: 0.5856 - value_head_loss: 0.0934 - policy_head_loss: 0.9612
Epoch 15/20
16/16 - 0s - loss: 0.5668 - value_head_loss: 0.0833 - policy_head_loss: 0.9352
Epoch 16/20
16/16 - 0s - loss: 0.5695 - value_head_loss: 0.0871 - policy_head_loss: 0.9399
Epoch 17/20
16/16 - 0s - loss: 0.5676 - value_head_loss: 0.0860 - policy_head_loss: 0.9391
Epoch 18/20
16/16 - 0s - loss: 0.5637 - value_head_loss: 0.0808 - policy_head_loss: 0.9388
Epoch 19/20
16/16 - 0s - loss: 0.5576 - value_head_loss: 0.0813 - policy_head_loss: 0.9298
Epoch 20/20
16/16 - 0s - loss: 0.5576 - value_head_loss: 0.0759 - policy_head_loss: 0.9388
Games played: 600
Epoch 1/20
16/16 - 0s - loss: 0.6858 - value_head_loss: 0.1604 - policy_

Games played: 1080
Epoch 1/20
16/16 - 0s - loss: 0.6718 - value_head_loss: 0.1948 - policy_head_loss: 1.0530
Epoch 2/20
16/16 - 0s - loss: 0.6397 - value_head_loss: 0.1608 - policy_head_loss: 1.0011
Epoch 3/20
16/16 - 0s - loss: 0.6073 - value_head_loss: 0.1544 - policy_head_loss: 0.9414
Epoch 4/20
16/16 - 0s - loss: 0.5910 - value_head_loss: 0.1490 - policy_head_loss: 0.9207
Epoch 5/20
16/16 - 0s - loss: 0.5708 - value_head_loss: 0.1354 - policy_head_loss: 0.9003
Epoch 6/20
16/16 - 0s - loss: 0.5606 - value_head_loss: 0.1249 - policy_head_loss: 0.8953
Epoch 7/20
16/16 - 0s - loss: 0.5494 - value_head_loss: 0.1143 - policy_head_loss: 0.8871
Epoch 8/20
16/16 - 0s - loss: 0.5546 - value_head_loss: 0.1100 - policy_head_loss: 0.9052
Epoch 9/20
16/16 - 0s - loss: 0.5597 - value_head_loss: 0.1136 - policy_head_loss: 0.9139
Epoch 10/20
16/16 - 0s - loss: 0.5579 - value_head_loss: 0.1147 - policy_head_loss: 0.9066
Epoch 11/20
16/16 - 0s - loss: 0.5463 - value_head_loss: 0.1060 - policy_head_lo

Epoch 11/20
16/16 - 0s - loss: 0.5468 - value_head_loss: 0.1128 - policy_head_loss: 0.9083
Epoch 12/20
16/16 - 0s - loss: 0.5451 - value_head_loss: 0.1148 - policy_head_loss: 0.9050
Epoch 13/20
16/16 - 0s - loss: 0.5440 - value_head_loss: 0.1104 - policy_head_loss: 0.9089
Epoch 14/20
16/16 - 0s - loss: 0.5491 - value_head_loss: 0.1147 - policy_head_loss: 0.9152
Epoch 15/20
16/16 - 0s - loss: 0.5508 - value_head_loss: 0.1146 - policy_head_loss: 0.9170
Epoch 16/20
16/16 - 0s - loss: 0.5440 - value_head_loss: 0.1088 - policy_head_loss: 0.9099
Epoch 17/20
16/16 - 0s - loss: 0.5365 - value_head_loss: 0.1051 - policy_head_loss: 0.9006
Epoch 18/20
16/16 - 0s - loss: 0.5426 - value_head_loss: 0.1157 - policy_head_loss: 0.9030
Epoch 19/20
16/16 - 0s - loss: 0.5504 - value_head_loss: 0.1148 - policy_head_loss: 0.9142
Epoch 20/20
16/16 - 0s - loss: 0.5510 - value_head_loss: 0.1097 - policy_head_loss: 0.9191
Games played: 1680
Epoch 1/20
16/16 - 0s - loss: 0.6680 - value_head_loss: 0.1905 - policy

In [10]:
alphazero.save('models/experiment_tictactoe_v2.h5')

In [7]:
#alphazero.set_max_iter(400)

play(game, Minimax(game), alphazero, games=10)

(6, 4, 0)

In [5]:
alphazero = AlphaZero(game, buffer_size=1024, mcts_iter=100)

In [6]:
alphazero.load('models/experiment_tictactoe_v2.h5')

In [8]:
mcts_draws = list()
az_draws = list()
minimax = Minimax(game)
iters = (2, 10, 50, 100, 200, 400)

for m in iters:
    mcts = MonteCarloTree(game, max_iter=m, reset_tree=False)
    _, draws, _ = play(game, minimax, mcts, games=100, max_workers=10)
    mcts_draws.append(draws)
    
    alphazero.set_max_iter(m)
    _, draws, _ = play(game, minimax, alphazero, games=100)
    az_draws.append(draws)

mcts_draws, az_draws

([0, 9, 35, 53, 60, 80], [79, 90, 86, 87, 85, 92])

In [25]:
import plotly.graph_objects as go


fig = go.Figure()
fig.add_trace(go.Scatter(x=iters, y=mcts_draws, mode='lines+markers', name='MCTS draws'))
fig.add_trace(go.Scatter(x=iters, y=az_draws, mode='lines+markers', name='AZ draws'))
fig.update_xaxes(title_text='Iterations')
fig.update_yaxes(title_text='Draws')
fig.show()

In [ ]:
from tfg.strategies import HumanStrategy


alphazero.set_max_iter(400)

play(game, HumanStrategy(game), alphazero, render=True, print_results=True)

 | | 
-+-+-
 | | 
-+-+-
 | | 


[PLAYER] choose action: 0, 1, 2, 3, 4, 5, 6, 7, 8
> 8
 | | 
-+-+-
 | | 
-+-+-
 | |X

O| | 
-+-+-
 | | 
-+-+-
 | |X


[PLAYER] choose action: 1, 2, 3, 4, 5, 6, 7


In [5]:
model = alphazero.neural_network.model

In [6]:
import numpy as np
board = np.array([[
    [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]],
    [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]],
    [[0] * 3] * 3
]])
v, p = model(board)
v = v.numpy()[0, 0]
p = p.numpy()[0]
v, p, np.argmax(p)

(-0.0033795643,
 array([0.09475057, 0.0194478 , 0.05071083, 0.06710757, 0.2650528 ,
        0.19979826, 0.08726399, 0.1512179 , 0.06465028], dtype=float32),
 4)

In [7]:
games = np.zeros((3, 3))

for i, g in enumerate(store.games):
    if i % 120 == 0:
        games[...] = 0
    games += g[1]
    if i % 120 == 119:
        print(games)
        print()

[[16. 11. 13.]
 [ 9. 14. 14.]
 [15. 15. 13.]]

[[10.  4.  6.]
 [ 4. 56.  0.]
 [18.  7. 15.]]

[[15. 20. 19.]
 [ 4. 22.  4.]
 [21.  8.  7.]]

[[35.  5. 18.]
 [10. 25.  7.]
 [ 4.  6. 10.]]

[[13.  5.  2.]
 [ 5. 79.  4.]
 [ 7.  2.  3.]]

[[17.  2.  5.]
 [ 4. 43.  5.]
 [23. 14.  7.]]

[[ 5.  4.  6.]
 [ 1. 71.  2.]
 [ 8. 17.  6.]]

[[29.  3. 11.]
 [ 4. 20.  3.]
 [10. 26. 14.]]

[[12.  6.  4.]
 [11. 19.  8.]
 [ 8. 45.  7.]]

[[ 5.  7. 12.]
 [16. 51.  3.]
 [ 5. 18.  3.]]

[[ 6.  6.  6.]
 [10. 71.  6.]
 [ 5.  9.  1.]]

[[14.  1. 54.]
 [16. 10.  4.]
 [ 6. 10.  5.]]

[[ 3.  2.  9.]
 [40. 22.  2.]
 [ 9.  4. 29.]]

[[ 1.  2.  7.]
 [10. 87.  1.]
 [ 6.  2.  4.]]

[[14.  1.  4.]
 [12. 44.  6.]
 [ 6. 27.  6.]]

[[13.  1.  2.]
 [ 6. 33. 33.]
 [ 4. 21.  7.]]



In [8]:
observation = game.reset()
alphazero.update(None)
observation, _, _, _ = game.step(8)
alphazero.update(8)
observation, _, _, _ = game.step(0)
alphazero.update(0)
game.render()
action = alphazero.move(observation)
game.step(action)
game.render()

O| | 
-+-+-
 | | 
-+-+-
 | |X

O| | 
-+-+-
 | | 
-+-+-
X| |X



In [9]:
actions = alphazero._mcts.stats['actions']
N = sum(n.visit_count for n in actions.values())
print("action  ", " pi ", "   P  ", "value", sep='    ')
for a, n in actions.items():
    print(f"action {a}", f"{n.visit_count / N:.3f}", f"{n.probability:.3f}", f"{n.value:.3f}", sep='    ')

action       pi        P      value
action 1    0.000    0.017    0.000
action 2    0.003    0.082    -0.454
action 3    0.003    0.087    -0.064
action 4    0.015    0.281    -0.040
action 5    0.015    0.240    0.038
action 6    0.965    0.264    0.832
action 7    0.000    0.029    0.000


In [44]:
alphazero._mcts._root.root

True